/* Задание 1 */
CREATE TABLE T_Messure(
  ID_Messure INT NOT NULL,
  Name NVARCHAR2(20) NOT NULL,
  CONSTRAINT PK_Messure 
    PRIMARY KEY (ID_MESSURE)
);
CREATE TABLE T_Material(
  ID_Material INT NOT NULL,
  Name NVARCHAR2(100) NOT NULL,
  ID_Messure INT NOT NULL,
  CONSTRAINT PK_Material 
    PRIMARY KEY (ID_MATERIAL),
  CONSTRAINT FK_Material_Messure 
    FOREIGN KEY (ID_MESSURE) REFERENCES T_MESSURE(ID_MESSURE)
);
CREATE TABLE T_InPrice(
  ID_Material INT NOT NULL,
  Price_Date DATE NOT NULL,
  Price NUMBER(10,2) CHECK (PRICE >= 0),
  CONSTRAINT FK_InPrice_Material
    FOREIGN KEY (ID_MATERIAL) REFERENCES T_MATERIAL(ID_MATERIAL) ON DELETE CASCADE
);
CREATE TABLE T_Store(
  ID_Store INT NOT NULL,
  Name NVARCHAR2(20) NOT NULL,
  CONSTRAINT PK_Store
    PRIMARY KEY (ID_STORE)
);
CREATE TABLE T_Caterer(
  ID_Caterer INT NOT NULL,
  Name NVARCHAR2(50) NOT NULL,
  Addres NVARCHAR2(100) NOT NULL,
  Phone NUMBER(11,0) NOT NULL,
  Fax NUMBER(20,0),
  CONSTRAINT PK_Caterer
    PRIMARY KEY (ID_CATERER)
);
CREATE TABLE T_Supply(
  ID_Supply INT NOT NULL,
  ID_Caterer INT NOT NULL,
  ID_Material INT NOT NULL,
  ID_Store INT NOT NULL,
  Supply_Date DATE NOT NULL,
  Volume INT NOT NULL,
  CONSTRAINT PK_Supply
    PRIMARY KEY (ID_SUPPLY),
  CONSTRAINT FK_Supply_Caterer
    FOREIGN KEY (ID_CATERER) REFERENCES T_CATERER(ID_CATERER),
  CONSTRAINT FK_Supply_Material
    FOREIGN KEY (ID_MATERIAL) REFERENCES T_MATERIAL(ID_MATERIAL),
  CONSTRAINT FK_Supply_Store
    FOREIGN KEY (ID_STORE) REFERENCES T_STORE(ID_STORE)
); 
CREATE TABLE T_Surplus(
  ID_Material INT NOT NULL,
  ID_Store INT NOT NULL,
  Volume INT CHECK (Volume >= 0),
  CONSTRAINT FK_Surplus_Material
    FOREIGN KEY (ID_MATERIAL) REFERENCES T_MATERIAL(ID_MATERIAL) ON DELETE CASCADE,
  CONSTRAINT FK_Surplus_Store
    FOREIGN KEY (ID_STORE) REFERENCES T_STORE(ID_STORE) ON DELETE CASCADE
);
CREATE TABLE T_Employer(
  ID_Employer INT NOT NULL,
  Name NVARCHAR2(20) NOT NULL,
  Surname NVARCHAR2(20) NOT NULL,
  Father_Name NVARCHAR2(20),
  CONSTRAINT PK_Employer
    PRIMARY KEY (ID_EMPLOYER)
);
CREATE TABLE T_Section(
  ID_Section INT NOT NULL,
  Name NVARCHAR2(50) NOT NULL,
  ID_Employer INT NOT NULL,
  CONSTRAINT PK_Section
    PRIMARY KEY (ID_SECTION),
  CONSTRAINT FK_Section_Employer
    FOREIGN KEY (ID_EMPLOYER) REFERENCES T_EMPLOYER(ID_EMPLOYER) ON DELETE CASCADE
);
CREATE TABLE T_Deliver(
  ID_Deliver INT NOT NULL,
  ID_Section INT NOT NULL,
  ID_Material INT NOT NULL,
  ID_Store INT NOT NULL,
  Deliver_Date DATE NOT NULL,
  CONSTRAINT PK_Deliver
    PRIMARY KEY (ID_DELIVER),
  CONSTRAINT FK_Deliver_Section
    FOREIGN KEY (ID_SECTION) REFERENCES T_SECTION(ID_SECTION) ON DELETE CASCADE,
  CONSTRAINT FK_Deliver_Material
    FOREIGN KEY (ID_MATERIAL) REFERENCES T_MATERIAL(ID_MATERIAL) ON DELETE CASCADE,
  CONSTRAINT FK_Deliver_Store
    FOREIGN KEY (ID_STORE) REFERENCES T_STORE(ID_STORE) ON DELETE CASCADE
);
/* Задание 2 */
ALTER TABLE T_CATERER
  DROP COLUMN ADDRES;
ALTER TABLE T_CATERER
  ADD (Legal_Addres NVARCHAR2(100) NOT NULL,
    Actual_Adders NVARCHAR2(100) NOT NULL,
    E_Mail NVARCHAR2(50));

/* Задание 3 */
ALTER TABLE T_INPRICE
  ADD CONSTRAINT PK_INPRICE
    PRIMARY KEY (ID_MATERIAL, PRICE_DATE);

/* Задание 4 */
CREATE TABLE T_Group(
  ID_Group INT NOT NULL,
  NAME NVARCHAR2(40) NOT NULL,
  CONSTRAINT PK_Group 
    PRIMARY KEY (ID_GROUP)
);
ALTER TABLE T_MATERIAL
  ADD ID_GROUP INT
  ADD CONSTRAINT FK_Material_Group
      FOREIGN KEY (ID_GROUP) REFERENCES T_GROUP(ID_GROUP) ON DELETE SET NULL;

/* Задание 5 */
ALTER TABLE T_CATERER
  MODIFY (FAX NVARCHAR2(30));
ALTER TABLE T_SUPPLY
  MODIFY (VOLUME INT CHECK (VOLUME >= 0))
